// <auto-generated />
using System;
using COINEXEN.Repository.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace COINEXEN.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230610120909_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("COINEXEN.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "1-Category-Description",
                            Name = "1-Category"
                        },
                        new
                        {
                            Id = 2,
                            Description = "2-Category-Description",
                            Name = "2-Category"
                        },
                        new
                        {
                            Id = 3,
                            Description = "3-Category-Description",
                            Name = "3-Category"
                        });
                });

            modelBuilder.Entity("COINEXEN.Core.Entities.Coin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A-Description",
                            Name = "ACoin",
                            Price = 1.6000000000000001,
                            ShortName = "a",
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "B-Description",
                            Name = "BCoin",
                            Price = 1.6000000000000001,
                            ShortName = "b",
                            Stock = 10
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "C-Description",
                            Name = "CCoin",
                            Price = 1.6000000000000001,
                            ShortName = "c",
                            Stock = 10
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "D-Description",
                            Name = "DCoin",
                            Price = 1.6000000000000001,
                            ShortName = "d",
                            Stock = 10
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "E-Description",
                            Name = "ECoin",
                            Price = 1.6000000000000001,
                            ShortName = "e",
                            Stock = 10
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "F-Description",
                            Name = "FCoin",
                            Price = 1.6000000000000001,
                            ShortName = "f",
                            Stock = 10
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "G-Description",
                            Name = "GCoin",
                            Price = 1.6000000000000001,
                            ShortName = "g",
                            Stock = 10
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "H-Description",
                            Name = "HCoin",
                            Price = 1.6000000000000001,
                            ShortName = "h",
                            Stock = 10
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "İ-Description",
                            Name = "İCoin",
                            Price = 1.6000000000000001,
                            ShortName = "i",
                            Stock = 10
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "J-Description",
                            Name = "JCoin",
                            Price = 1.6000000000000001,
                            ShortName = "j",
                            Stock = 10
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "K-Description",
                            Name = "KCoin",
                            Price = 1.6000000000000001,
                            ShortName = "k",
                            Stock = 10
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "L-Description",
                            Name = "LCoin",
                            Price = 1.6000000000000001,
                            ShortName = "l",
                            Stock = 10
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "M-Description",
                            Name = "MCoin",
                            Price = 1.6000000000000001,
                            ShortName = "m",
                            Stock = 10
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Description = "N-Description",
                            Name = "NCoin",
                            Price = 1.6000000000000001,
                            ShortName = "n",
                            Stock = 10
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Description = "O-Description",
                            Name = "OCoin",
                            Price = 1.6000000000000001,
                            ShortName = "o",
                            Stock = 10
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Description = "P-Description",
                            Name = "PCoin",
                            Price = 1.6000000000000001,
                            ShortName = "p",
                            Stock = 10
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Description = "Q-Description",
                            Name = "QCoin",
                            Price = 1.6000000000000001,
                            ShortName = "q",
                            Stock = 10
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Description = "R-Description",
                            Name = "RCoin",
                            Price = 1.6000000000000001,
                            ShortName = "r",
                            Stock = 10
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Description = "S-Description",
                            Name = "SCoin",
                            Price = 1.6000000000000001,
                            ShortName = "s",
                            Stock = 10
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Description = "T-Description",
                            Name = "TCoin",
                            Price = 1.6000000000000001,
                            ShortName = "t",
                            Stock = 10
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            Description = "U-Description",
                            Name = "UCoin",
                            Price = 1.6000000000000001,
                            ShortName = "u",
                            Stock = 10
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            Description = "V-Description",
                            Name = "VCoin",
                            Price = 1.6000000000000001,
                            ShortName = "v",
                            Stock = 10
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            Description = "X-Description",
                            Name = "XCoin",
                            Price = 1.6000000000000001,
                            ShortName = "x",
                            Stock = 10
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            Description = "Y-Description",
                            Name = "YCoin",
                            Price = 1.6000000000000001,
                            ShortName = "y",
                            Stock = 10
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            Description = "Z-Description",
                            Name = "ZCoin",
                            Price = 1.6000000000000001,
                            ShortName = "z",
                            Stock = 10
                        });
                });

            modelBuilder.Entity("COINEXEN.Core.Entities.CoinTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("CoinId")
                        .HasColumnType("int");

                    b.Property<double>("CoinPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateOfTransaction")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Transaction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CoinId");

                    b.ToTable("CoinTransactions");
                });

            modelBuilder.Entity("COINEXEN.Core.Entities.Identity.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("COINEXEN.Core.Entities.Identity.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Birthday")
                        .HasColumnType("int");

                    b.Property<int>("City")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("COINEXEN.Core.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("City")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SendingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopicTitle")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("COINEXEN.Core.Entities.Wallet.CoinWallet", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CoinWallets");
                });

            modelBuilder.Entity("COINEXEN.Core.Entities.Wallet.CoinWalletLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoinId")
                        .HasColumnType("int");

                    b.Property<int>("CoinWalletId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoinId");

                    b.HasIndex("CoinWalletId");

                    b.ToTable("CoinWalletLines");
                });

            modelBuilder.Entity("COINEXEN.Core.Entities.Wallet.UserWallet", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("UserWallets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("COINEXEN.Core.Entities.Coin", b =>
                {
                    b.HasOne("COINEXEN.Core.Entities.Category", "Category")
                        .WithMany("Coins")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("COINEXEN.Core.Entities.CoinTransaction", b =>
                {
                    b.HasOne("COINEXEN.Core.Entities.Identity.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COINEXEN.Core.Entities.Coin", "Coin")
                        .WithMany()
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Coin");
                });

            modelBuilder.Entity("COINEXEN.Core.Entities.Wallet.CoinWallet", b =>
                {
                    b.HasOne("COINEXEN.Core.Entities.Identity.AppUser", "AppUser")
                        .WithOne("CoinWallet")
                        .HasForeignKey("COINEXEN.Core.Entities.Wallet.CoinWallet", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("COINEXEN.Core.Entities.Wallet.CoinWalletLine", b =>
                {
                    b.HasOne("COINEXEN.Core.Entities.Coin", "Coin")
                        .WithMany()
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COINEXEN.Core.Entities.Wallet.CoinWallet", "CoinWallet")
                        .WithMany("CoinWalletLines")
                        .HasForeignKey("CoinWalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coin");

                    b.Navigation("CoinWallet");
                });

            modelBuilder.Entity("COINEXEN.Core.Entities.Wallet.UserWallet", b =>
                {
                    b.HasOne("COINEXEN.Core.Entities.Identity.AppUser", "AppUser")
                        .WithOne("Wallet")
                        .HasForeignKey("COINEXEN.Core.Entities.Wallet.UserWallet", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("COINEXEN.Core.Entities.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("COINEXEN.Core.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("COINEXEN.Core.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("COINEXEN.Core.Entities.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COINEXEN.Core.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("COINEXEN.Core.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("COINEXEN.Core.Entities.Category", b =>
                {
                    b.Navigation("Coins");
                });

            modelBuilder.Entity("COINEXEN.Core.Entities.Identity.AppUser", b =>
                {
                    b.Navigation("CoinWallet");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("COINEXEN.Core.Entities.Wallet.CoinWallet", b =>
                {
                    b.Navigation("CoinWalletLines");
                });
#pragma warning restore 612, 618
        }
    }
}
